logging:
  level:
    xiang:
      fr: debug
spring:
  flyway:
    enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true